### ISSUE TITLE
Lỗi hàng nghìn tỷ

### ISSUE THREAD

**Issue by drducmanh** [hankphung/numer_to_vietnamese_text#1]
Ví dụ: 1230950880055 lẽ ra phải là: "một nghìn hai trăm 30 tỷ, chín trăm năm mươi triệu, tám trăm tám mươi nghìn, không trăm năm mươi lăm đồng "
Nhưng chạy: to_vietnamese(1230950880055) sẽ ra: "một hai trăm ba mươi tỷ chín trăm năm mươi triệu tám trăm tám mươi nghìn không trăm năm mươi lăm đồng"

Dưới một nghìn tỷ thì vẫn OK, nhưng đến hàng nghìn tỷ là lỗi nhé bạn!

**Comment by hankphung** [comment]
Cảm ơn bạn. lỗi đã được sửa bằng commit https://github.com/hankphung/numer_to_vietnamese_text/commit/aa46b596738d9a6e111e1efb840310b515833fda
